version: '3'
services:

  zookeeper:
    image: eventuateio/eventuate-zookeeper:0.16.0.RELEASE
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
      image: eventuateio/eventuate-kafka:0.16.0.RELEASE
      depends_on:
        - zookeeper
      ports:
        - 9092:9092
        - 29092:29092
      environment:
        KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
        KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: LC
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_HEAP_OPTS: -Xmx192m


  postgres:
    image: eventuateio/eventuate-tram-sagas-postgres:0.20.0.RELEASE
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eventuate
      POSTGRES_PASSWORD: eventuate

  order-postgres:
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:1
    ports:
      - 5433:5432
    environment:
      POSTGRESQL_USER: admin
      POSTGRESQL_PASSWORD: admin
      POSTGRESQL_ADMIN_PASSWORD: admin
      POSTGRESQL_DATABASE: order

  customer-postgres:
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:1
    ports:
      - 5434:5432
    environment:
      POSTGRESQL_USER: admin
      POSTGRESQL_PASSWORD: admin
      POSTGRESQL_ADMIN_PASSWORD: admin
      POSTGRESQL_DATABASE: customer

  cdc-service:
    image: eventuateio/eventuate-cdc-service:0.14.0.RELEASE
    ports:
      - "8099:8080"
    depends_on:
      - postgres
      - kafka
      - zookeeper
    environment:
      EVENTUATE_CDC_READER_READER1_TYPE: polling
      EVENTUATE_CDC_READER_READER1_DATASOURCEURL: jdbc:postgresql://order-postgres/order?currentSchema=eventuate
      EVENTUATE_CDC_READER_READER1_DATASOURCEUSERNAME: admin
      EVENTUATE_CDC_READER_READER1_DATASOURCEPASSWORD: admin
      EVENTUATE_CDC_READER_READER1_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATE_CDC_READER_READER1_OUTBOXID: 1
      EVENTUATE_CDC_READER_READER1_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/eventuatetram
      EVENTUATE_CDC_PIPELINE_PIPELINE1_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE1_READER: reader1
      EVENTUATE_CDC_READER_READER2_TYPE: polling
      EVENTUATE_CDC_READER_READER2_DATASOURCEURL: jdbc:postgresql://customer-postgres/customer?currentSchema=eventuate
      EVENTUATE_CDC_READER_READER2_DATASOURCEUSERNAME: admin
      EVENTUATE_CDC_READER_READER2_DATASOURCEPASSWORD: admin
      EVENTUATE_CDC_READER_READER2_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATE_CDC_READER_READER2_OUTBOXID: 1
      EVENTUATE_CDC_READER_READER2_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/eventuatetram
      EVENTUATE_CDC_PIPELINE_PIPELINE2_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE2_READER: reader2
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      JAVA_OPTS: -Xmx64m
